services:
  redis:
    image: redis:7
    container_name: sentinel2_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  seed-redis:
    build: .
    container_name: sentinel2_seed_redis
    command: python seed_redis.py
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy

  batch:
    build: .
    container_name: sentinel2_batch
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
